# Generated by Django 2.2.5 on 2021-11-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20211128_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guset',
            new_name='guest',
        ),
    ]
